version: 0.2

phases:
  install:
    runtime-versions:
      dotnet: 7.0 # Change to your desired .NET Core version

  pre_build:
    commands:
      - echo "Restoring dependencies"
      - dotnet restore

  build:
    commands:
      - echo "Building the .NET Core Web API app"
      - dotnet build --configuration Release

  post_build:
    commands:
      - echo "Running unit tests"
      - dotnet test --configuration Release

artifacts:
  files:
    - '**/bin/Release/net7.0/**' # Adjust the path based on your project structure
  base-directory: ./Notes.API # Adjust the base directory based on your project structure
  discard-paths: no
